[package]
name = "investment_calculator"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-cors = "0.7.0"
actix-web = { version = "4.9.0", features = ["rustls-0_23"] }
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
